Item_Review/config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  root to: 'homes#top'
  get "search" => "searches#search"

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'user/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    resources :items, only: [:index, :show, :new, :edit, :create, :update] do
      resources :reviews, only: [:index, :show, :create] do
        resources :comments, only: [:index, :create]
      end
    end
    resources :users, only: [:index, :show, :edit, :update] do
      member do
      get :follows, :followers
      end
      resource :relationships, only: [:create, :destroy]
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
    end
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update] do
      resources :reviews, only: [:index, :destroy] do
        resources :comments, only: [:index, :destroy]
      end
    end
    resources :users, only: [:index, :show, :update]
    resources :categories, only: [:index, :create, :edit, :update]
  end

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Item_Review/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

Item_Review/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Item_Review/app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :item_categories, dependent: :destroy
  has_many :items, through: :item_categories

end

Item_Review/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review
  belongs_to :item
  validates :content, presence: true
end

Item_Review/app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :item_categories, dependent: :destroy
  has_many :categories, through: :item_categories
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy

  def self.looks(search, word)
    if search == "perfect_match"
      @item = Item.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @item = Item.where("name LIKE?","%#{word}%")
    else
      @item = Item.all
    end
  end
end

Item_Review/app/models/item_category.rb
class ItemCategory < ApplicationRecord
  belongs_to :item
  belongs_to :category
end

Item_Review/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

Item_Review/app/models/review.rb
class Review < ApplicationRecord
belongs_to :user
belongs_to :item
has_many :comments, dependent: :destroy
validates :star, :article, presence: true
end

Item_Review/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :image
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  

  GUEST_USER_EMAIL = "guest@example.com"
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

Item_Review/app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @item = Item.new
  end

  def index
    if params[:category_id].present?
      @category = Category.find(params[:category_id])
      @items = @category.items
    else
      @items = Item.all
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
      flash[:notice] = "新たにアイテムを追加しました。"
    else
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
      flash[:notice] = "アイテム情報を更新しました。"
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :category_id, :introduction, :price, :on_sale, :image, category_ids:[])
  end

end

Item_Review/app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @review = @user.reviews
  end

  def follows
    @user = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

  def update
    @users = User.find(params[:id])
    if @users.update(user_params)
      redirect_to admin_users_path(@users), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile, :email, :is_active, :image)
  end
end

Item_Review/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!, if: :admin_url

  def admin_url
    request.fullpath.include?("/admin")
  end
end

Item_Review/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

end

Item_Review/app/controllers/searches_controller.rb
class SearchesController < ApplicationController
before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @items = Item.looks(params[:search], params[:word])
    end
  end
end

Item_Review/app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

Item_Review/app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

Item_Review/app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

Item_Review/app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

Item_Review/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

Item_Review/app/helpers/application_helper.rb
module ApplicationHelper
end

Item_Review/app/helpers/homes_helper.rb
module HomesHelper
end

Item_Review/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

Item_Review/app/helpers/searches_helper.rb
module SearchesHelper
end

Item_Review/app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <h4 class="my-3 bg-light">アイテム編集</h4>
  </div>
  <div class="row">
    <%= form_with model: @item, url: admin_item_path(@item), method: :patch, local: true, class: "mx-auto" do |f| %>
    <% render "admin/shared/error_messages", resource: @item %>
    <!-- 商品画像の更新 -->
    <strong class="my-2 col-sm-3">アイテム画像</strong>
    <div class="my-2 col-sm-9">
      <%= f.file_field :image %>
    </div>
    <!-- 商品名の更新 -->
    <strong class="my-2 col-sm-3">アイテム名</strong>
    <div class="my-2 col-sm-9">
      <%= f.text_field :name, size:"56x5" %>
    </div>
    <!-- 商品説明の更新 -->
    <strong class="my-2 col-sm-3">アイテム品説明</strong>
    <div class="my-2 col-sm-9">
      <%= f.text_area :introduction, size:"55x5" %>
    </div>
    <!-- 商品ジャンルの更新 -->
    <strong class="my-2 col-sm-3">カテゴリー</strong>
    <div class="my-2 col-sm-9">
      <%= f.collection_select :category_ids, Category.all, :id,:name,{prompt: "--選択してください--"}, {multiple: true} %>
      <%= link_to "カテゴリーの追加", admin_categories_path, class:"btn btn-success ml-3" %>
    </div>
    <!-- 商品税抜価格の更新 -->
    <strong class="my-2 col-sm-3">価格</strong>
    <div class="my-2 col-sm-9">
      <%= f.text_field :price %>
    </div>
    <!-- 商品販売ステータスの更新 -->
    <strong class="my-2 col-sm-3">発売日</strong>
    <div class="my-2 col-sm-9">
      <%= f.date_field :on_sale %>
    </div>
    <div class="my-2 col-lg-3"></div>
    <div class="my-2 col-lg-9"><%= f.submit "変更内容を保存", class: "btn btn-success" %></div>
    <% end %>
    </div>
</div>

Item_Review/app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <h4>アイテム一覧</h4>
  <div>
  </div>
    <div>
      <%= link_to new_admin_item_path do %>
        <button type="button">
          ＋
        </button>
      <% end %>
    </div>
  </div>
  <div class="d-flex justify-content-end">
  <%= form_with url: admin_items_path, method: :get, local: true, class: 'boards__searchForm' do |f|%>
      <%= select_tag :category_id,
        options_from_collection_for_select(Category.all, :id, :name, params[:category_id]),
          {
            prompt: "カテゴリーで絞り込み",
            onchange: "submit(this.form);"
          }
      %>
  <% end %>
</div>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th>アイテム画</th>
        <th>アイテム名</th>
        <th>価格</th>
        <th>カテゴリー</th>
        <th>販売開始日</th>
        <th></th>
      </tr>
    </thead>
    <% @items.each do |item| %>
      <tr>
        <td>
          <%= link_to admin_item_path(item.id) do %>
            <% if item.image.attached? %>
              <%= image_tag item.image, size: "100x100" %>
            <% else %>
              <%= image_tag 'no-image.jpg', size: "100x100" %>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= link_to admin_item_path(item.id) do %>
          <%= item.name %>
          <% end %>
        </td>
        <td><%= item.price %></td>
        <td>
            <%= item.categories.pluck(:name).join(",") %>
        </td>
        <td><%= item.on_sale %></td>
        <td><%= link_to "レビューを見る", admin_item_reviews_path(item), class: "button light ml-3 mt-3" %></td>
      </tr>
    <% end %>
  </table>
</div>

Item_Review/app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <h4 class="my-3 bg-light">アイテム新規登録</h4>
  </div>
  <div class="row">
    <%= form_with model: [:admin, @item], local: true, class: 'mx-auto' do |f| %>
    <!--  商品画像の追加 -->
    <strong class="my-2 col-sm-3">アイテム画像</strong>
    <div class="my-2 col-sm-9">
      <%= f.file_field :image %>
    </div>
    <!--  商品名の追加 -->
    <strong class="my-2 col-sm-3">アイテム名</strong>
    <div class="my-2 col-sm-9">
      <%= f.text_field :name, size:"56x5" %>
    </div>
    <!--  商品説明の追加 -->
    <strong class="my-2 col-sm-3">アイテム説明</strong>
    <div class="my-2 col-sm-9">
      <%= f.text_area :introduction, size:"55x5" %>
    </div>

    <strong class="my-2 col-sm-3">カテゴリー</strong>
    <div class="my-2 col-sm-9">
      <%= f.collection_select :category_ids, Category.all, :id,:name,{prompt: "--選択してください--"}, {multiple: true} %>
      <%= link_to "カテゴリーの追加", admin_categories_path, class:"btn btn-success ml-3" %>
    </div>

    <!--  商品税抜価格の追加 -->
    <strong class="my-2 col-sm-3">税抜価格</strong>
    <div class="my-2 col-sm-9">
      <%= f.text_field :price %>
    </div>

    <!--  商品税抜価格の追加 -->
    <strong class="my-2 col-sm-3">発売日</strong>
    <div class="my-2 col-sm-9">
      <%= f.date_field :on_sale %>
    </div>

    <!--  -->
    <div class="my-2 col-lg-3"></div>
    <div class="my-2 col-lg-9"><%= f.submit "新規登録", class: "btn btn-success" %></div>
    <% end %>
    </div>
</div>

Item_Review/app/views/admin/items/show.html.erb
<div class="container">
    <h4>アイテム詳細</h4>
  <div class="row">
    <img class="col-sm-4" style="width: 300px; height: 300px;" src="<%= url_for(@item.image) %>">
    <div class="col-sm-8">
      <!-- 商品名の表示 -->
      <strong class="col-sm-3">アイテム名</strong>
      <div class="my-2 col-sm-9"><%= @item.name %></div>
      <!-- 商品説明の表示 -->
      <strong class="col-sm-3">アイテム説明</strong>
      <div class="my-2 col-sm-6"><%= @item.introduction %></div>
      <!-- 商品ジャンルの表示 -->
      <strong class="col-sm-3">カテゴリー</strong>
      <div class="my-2 col-sm-9"><%= @item.categories.pluck(:name).join(",") %></div>
      <!-- 商品価格の表示 -->
      <strong class="col-sm-3">価格</strong>
      <div class="my-2 col-sm-9">
        <%= (@item.price).floor.to_s(:delimited) %>円
      </div>
      <strong class="col-sm-3">販売開始日</strong>
      <div class="my-2 col-sm-9"><%= @item.on_sale %></div>
      <!--  -->
      <div class="col-sm-3">
        <%= link_to "編集する",edit_admin_item_path(@item), class:"btn btn-success" %>
      </div>
    </div>
    <div type="button" class="btn btn-info">
    <%= link_to "レビューを見る", admin_item_reviews_path(@item), class: "text-white" %>
    </div>
  </div>
</div>

Item_Review/app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <h4 class="my-5 bg-light">ユーザー一覧</h4>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
        <th>ユーザー名</th>
        <th>メールアドレス</th>
        <th>フォロー</td>
        <th>フォロワー</td>
        <th>ステータス</th>
      </tr>
    </thead>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= link_to admin_user_path(user.id) do %>
            <% if user.image.attached? %>
              <%= image_tag user.image, size: "100x100" %>
            <% else %>
              <%= image_tag 'no-image.jpg', size: "100x100" %>
            <% end %>
          <% end %></td>
        <td>
          <%= link_to admin_user_path(user.id) do %>
          <%= user.name %>
          <% end %>
        </td>
        <td><%= user.email %></td>
        <td><%= user.followings.count %></td>
        <td><%= user.followers.count %></td>
        <td class="<%= user.is_active ? 'text-green' : 'text-greay' %>"><%= user.is_active ? '有効' : '制限' %></td>
      </tr>
    <% end %>
  </table>
</div>

Item_Review/app/views/admin/users/show.html.erb
<div class="container mt-5">
  <div class="row">
    <%= form_with model: @user, url: admin_user_path(@user), method: :patch, local: true do |f| %>
  <h2 class="my-3 bg-light"><%= @user.name %>さんの会員詳細</h2>
  <div class="row">
    <!-- 会員IDの表示 -->
    <span class="my-2 col-sm-9">
    <% if @user.image.attached? %>
      <%= image_tag @user.image, size: "200x200" %>
    <% else %>
      <%= image_tag 'no-image.jpg', size: "200x200" %>
    <% end %></span>
    <table class="table table-hover table-inverse">
    <tr>
      <td>ネーム</td>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <td>プロフィール</td>
      <td><%= @user.plofile %></td>
    </tr>
    <tr>
      <td class="bg-light col-md-3">メールアドレス</td>
      <td><%= @user.email %></td>
    </tr>
  </table>

  <strong class="my-2 col-sm-3">会員ステータスの更新</strong>
    <div class="my-2 col-sm-9">
      <%= f.radio_button :is_active, "ture" %>
      <%= f.label :is_active, "有効" %>
      <%= f.radio_button :is_active, "false" %>
      <%= f.label :is_active, "制限" %>
    </div>
    <!-- 更新ボタンの調整 -->
    <div class="my-2 col-lg-3"></div>
    <div class="my-2 col-lg-9"><%= f.submit "変更を保存", class: "btn btn-success" %></div>
  </div>
  <% end %>
  <strong><%= @user.name %>さんのレビュー一覧</strong>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th>アイテム名</th>
        <th>評価</th>
        <th>内容</th>
        <th></th>
      </tr>
    </thead>
    <% @review.each do |review| %>
    <tbody>
      <td>
        <%= link_to item_path(review.item.id) do %>
          <%= review.item.name %>
        <% end %>
      </td>
      <td>
        <div id="star_<%= review.id %>"></div>
        <script>
          $(document).on('turbolinks:load', function() {
          let elem = document.querySelector('#star_<%= review.id %>');
          if (elem == null) return;
            elem.innerHTML = "";
            let opt = {
              starOn: "<%= asset_path('star-on.png') %>",
              starOff: "<%= asset_path('star-off.png') %>",
              starHalf: "<%= asset_path('star-half.png') %>",
              score: "<%= review.star %>",
              readOnly: true,
            };
            raty(elem, opt);
          });
        </script>
      </td>
      <td>
        <%= review.article %>
      </td>
      <td><%= link_to "同アイテムの他レビューを見る", admin_item_reviews_path(review.item), class: "button light ml-3 mt-3" %></td>
    </tbody>
    <% end %>
  </table>
</div>