Item_Review/config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  root to: 'homes#top'
  get "search" => "searches#search"

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'user/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    resources :items, only: [:index, :show, :new, :edit, :create, :update] do
      resources :reviews, only: [:index, :show, :create] do
        resources :comments, only: [:index, :create]
      end
    end
    resources :users, only: [:index, :show, :edit, :update] do
      member do
      get :follows, :followers
      end
      resource :relationships, only: [:create, :destroy]
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
    end
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update] do
      resources :reviews, only: [:index, :destroy] do
        resources :comments, only: [:index, :destroy]
      end
    end
    resources :users, only: [:index, :show, :update]
    resources :categories, only: [:index, :create, :edit, :update]
  end

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Item_Review/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

Item_Review/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Item_Review/app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :item_categories, dependent: :destroy
  has_many :items, through: :item_categories

end

Item_Review/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review
  belongs_to :item
  validates :content, presence: true
end

Item_Review/app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :item_categories, dependent: :destroy
  has_many :categories, through: :item_categories
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy

  def self.looks(search, word)
    if search == "perfect_match"
      @item = Item.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @item = Item.where("name LIKE?","%#{word}%")
    else
      @item = Item.all
    end
  end
end

Item_Review/app/models/item_category.rb
class ItemCategory < ApplicationRecord
  belongs_to :item
  belongs_to :category
end

Item_Review/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

Item_Review/app/models/review.rb
class Review < ApplicationRecord
belongs_to :user
belongs_to :item
has_many :comments, dependent: :destroy
validates :star, :article, presence: true
end

Item_Review/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :image
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  

  GUEST_USER_EMAIL = "guest@example.com"
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

Item_Review/app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @item = Item.new
  end

  def index
    if params[:category_id].present?
      @category = Category.find(params[:category_id])
      @items = @category.items
    else
      @items = Item.all
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
      flash[:notice] = "新たにアイテムを追加しました。"
    else
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
      flash[:notice] = "アイテム情報を更新しました。"
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :category_id, :introduction, :price, :on_sale, :image, category_ids:[])
  end

end

Item_Review/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!, if: :admin_url

  def admin_url
    request.fullpath.include?("/admin")
  end
end

Item_Review/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

end

Item_Review/app/controllers/searches_controller.rb
class SearchesController < ApplicationController
before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @items = Item.looks(params[:search], params[:word])
    end
  end
end

Item_Review/app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

Item_Review/app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

Item_Review/app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

Item_Review/app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

Item_Review/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

Item_Review/app/helpers/application_helper.rb
module ApplicationHelper
end

Item_Review/app/helpers/homes_helper.rb
module HomesHelper
end

Item_Review/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

Item_Review/app/helpers/searches_helper.rb
module SearchesHelper
end

Item_Review/app/views/homes/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
    <%= f.text_field :word %>
    <%= f.select :range, options_for_select([['User'], ['Item']]) %>
    <%= f.select :search, options_for_select([["完全一致","perfect_match"],  ["部分一致","partial_match"]]) %>
    <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

Item_Review/app/views/homes/top.html.erb
<div class="container">
  <p>
   <%= flash[:notice] %>
  </p>
  <div class="text-center">
    <h1>シェアきゃん</h1>
    <p>ここでは様々なキャンプグッズの詳細、使用感等の共有を行えるサイトです。</p>
    <p>ユーザー登録をすればアイテムぼ追加やレビュー・コメント行う事ができます。</p>
    <p>ゲストログインも可能で制限はありますがサイトの閲覧ができます。</p>
  </div>
</div>

Item_Review/app/views/searches/search.html.erb
<div class="container">
  <div class="row">
<h2>検索結果</h2>

<table class="table table-hover table-inverse">
  <!--検索対象モデルがUserの時 -->
  <% if @range == "User" %>
    <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
        <th>ユーザー名</th>
        <th>プロフィール</th>
        <th>レビュー数</th>
        <th>フォロー</th>
        <th>フォロワー</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><% if user.image.attached? %>
          <%= image_tag user.image, size: "100x100" %>
          <% else %>
          <%= image_tag 'no-image.jpg', size: "100x100" %>
          <% end %>
          </td>
          <td>
            <%= link_to user_path(user.id) do %>
            <%= user.name %>
            <% end %>
          </td>
          <td><%= user.plofile %></td>
          <td><%= user.reviews.count %></td>
          <td><%= user.followings.count %></td>
          <td><%= user.followers.count %></td>
          <td>
          <% if !current_user.guest_user? %>
              <% if !(user.id == current_user.id) && !user.guest_user? %>
                <div type="button" class="btn btn-info">
                <% if current_user.following?(user) %>
                  <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class:"text-white" %>
                <% else %>
                  <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class:"text-white" %>
                <% end %>
              <% end %>
              </div>
            <% end %>
            </td>
        </tr>
      <% end %>
    </tbody>
    </table>
  <% else %>
    <!--検索対象モデルがUserではない時(= 検索対象モデルがitemの時) -->
    <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
        <th>アイテム名</th>
        <th>価格</th>
        <th>カテゴリー</th>
        <th>販売開始日</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td>
            <% if item.image.attached? %>
              <%= image_tag item.image, size: "100x100" %>
            <% else %>
              <%= image_tag 'no-image.jpg', size: "100x100" %>
            <% end %>
          </td>
          <td><%= link_to item_path(item.id) do %>
          <%= item.name %>
          <% end %>
          </td>
          <td><%= item.price %></td>
          <td>
            <%= item.categories.pluck(:name).join(",") %>
        </td>
        <td><%= item.on_sale %></td>
        <td><%= link_to "レビューを見る", item_reviews_path(item), class: "button light ml-3 mt-3" %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>
</div>
</div>