Item_Review/config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  root to: 'homes#top'
  get "search" => "searches#search"

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'user/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  scope module: :public do
    resources :items, only: [:index, :show, :new, :edit, :create, :update] do
      resources :reviews, only: [:index, :show, :create] do
        resources :comments, only: [:index, :create]
      end
    end
    resources :users, only: [:index, :show, :edit, :update] do
      member do
      get :follows, :followers
      end
      resource :relationships, only: [:create, :destroy]
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
    end
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update] do
      resources :reviews, only: [:index, :destroy] do
        resources :comments, only: [:index, :destroy]
      end
    end
    resources :users, only: [:index, :show, :update]
    resources :categories, only: [:index, :create, :edit, :update]
  end

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Item_Review/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

Item_Review/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Item_Review/app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :item_categories, dependent: :destroy
  has_many :items, through: :item_categories

end

Item_Review/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review
  belongs_to :item
  validates :content, presence: true
end

Item_Review/app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :item_categories, dependent: :destroy
  has_many :categories, through: :item_categories
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy

  def self.looks(search, word)
    if search == "perfect_match"
      @item = Item.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @item = Item.where("name LIKE?","%#{word}%")
    else
      @item = Item.all
    end
  end
end

Item_Review/app/models/item_category.rb
class ItemCategory < ApplicationRecord
  belongs_to :item
  belongs_to :category
end

Item_Review/app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

Item_Review/app/models/review.rb
class Review < ApplicationRecord
belongs_to :user
belongs_to :item
has_many :comments, dependent: :destroy
validates :star, :article, presence: true
end

Item_Review/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :image
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  

  GUEST_USER_EMAIL = "guest@example.com"
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

Item_Review/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!, if: :admin_url

  def admin_url
    request.fullpath.include?("/admin")
  end
end

Item_Review/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

end

Item_Review/app/controllers/searches_controller.rb
class SearchesController < ApplicationController
before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @items = Item.looks(params[:search], params[:word])
    end
  end
end

Item_Review/app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

Item_Review/app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

Item_Review/app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

Item_Review/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

Item_Review/app/helpers/application_helper.rb
module ApplicationHelper
end

Item_Review/app/helpers/homes_helper.rb
module HomesHelper
end

Item_Review/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

Item_Review/app/helpers/searches_helper.rb
module SearchesHelper
end

Item_Review/app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

Item_Review/app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

Item_Review/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>シェアきゃん</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg ">
        <div class="container">

        <ul class="nav-item nav navbar-nav navbar-right">
          <!-- ユーザーサインイン時のヘッダー -->
          <% if user_signed_in? %>
            <% if !current_user.guest_user? %>
              <li type="button" class="btn btn-outline-dark mr-3"><%= link_to 'マイページ', user_path(current_user.id), class:"nav-link"%></li>
            <% end %>
            <li type="button" class="btn btn-outline-dark mr-3"><%= link_to 'ユーザー一覧', users_path, class:"nav-link" %></li>
            <li type="button" class="btn btn-outline-dark mr-3"><%= link_to 'アイテム一覧', items_path, class:"nav-link" %></li>
            <li type="button" class="btn btn-outline-dark"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"nav-link" %></li>
          <!-- アドミンサインイン時のヘッダー -->
          <% elsif admin_signed_in? %>
            <li type="button" class="btn btn-outline-dark mr-3"><%= link_to 'アイテム一覧', admin_items_path, class:"nav-link" %></li>
            <li type="button" class="btn btn-outline-dark mr-3"><%= link_to '会員一覧', admin_users_path, class:"nav-link" %></li>
            <li type="button" class="btn btn-outline-dark mr-3"><%= link_to 'カテゴリー一覧', admin_categories_path, class:"nav-link" %></li>
            <li type="button" class="btn btn-outline-dark"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class:"nav-link" %></li>
          <!-- ログアウト時のヘッダー -->
          <% else %>
            <li type="button" class="btn btn-outline-dark mr-3"><%= link_to "新規登録", new_user_registration_path, class:"nav-link" %></li>
            <li type="button" class="btn btn-outline-dark"><%= link_to "ログイン", new_user_session_path, class:"nav-link" %></li>
          <% end %>
        </ul>
          <%= render 'homes/search' %>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>